In [1]:
import numpy as np

In [2]:
my_list = [1, 2, 3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
np.array([[1,2,3], [4, 5, 6], [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0, 10, 3)

array([0, 3, 6, 9])

In [13]:
np.zeros((5, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [17]:
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [20]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
np.random.rand(5)

array([0.09709844, 0.22579779, 0.9208813 , 0.94243743, 0.12331376])

In [26]:
np.random.rand(5,3)

array([[0.49651434, 0.11265741, 0.2709732 ],
       [0.02288338, 0.15332931, 0.28883405],
       [0.40801888, 0.8710852 , 0.45488921],
       [0.52776103, 0.89349547, 0.26600096],
       [0.34196359, 0.24680058, 0.02395609]])

In [28]:
np.random.randn(10)

array([ 1.8211693 , -0.84682961, -0.15164487,  1.11986562, -0.11229106,
        1.73542404,  0.60787069,  0.4083565 , -1.0629519 , -2.30351066])

In [30]:
np.random.randn(5,3)

array([[-0.86051963,  0.30107   , -0.2235843 ],
       [ 1.64506209,  0.10554553,  0.49152154],
       [ 0.51150803,  0.83019683,  1.52474002],
       [-0.35806356, -1.00546885, -1.36063664],
       [ 0.12120132,  0.08128444, -0.82376523]])

In [36]:
np.random.randint(1,100, 3)

array([88, 46,  2])

In [38]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [39]:
ran_arr = np.random.randint(1,100,10)
ran_arr

array([73, 73, 44, 96, 62, 86, 47,  8, 86, 17])

In [43]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [44]:
ran_arr.min()

8

In [45]:
ran_arr.max()

96

In [46]:
ran_arr.argmax()

3

In [47]:
ran_arr.argmin()

7

In [49]:
ran_arr.shape

(10,)

In [50]:
arr.shape

(25,)

In [51]:
arr.reshape(5,5).shape

(5, 5)

In [52]:
arr.dtype

dtype('int64')

In [55]:
arr[9:11]

array([ 9, 10])

In [59]:
arr[:9] = 100
arr

array([100, 100, 100, 100, 100, 100, 100, 100, 100,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [61]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [63]:
arr_copy = arr.copy()
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [66]:
arr_copy[:9] = 10
arr_copy

array([10, 10, 10, 10, 10, 10, 10, 10, 10,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [67]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [78]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [88]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

In [77]:
arr_2d[:1]

array([[ 5, 10, 15]])

In [81]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

In [17]:
arr2d = np.zeros((10,10))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [18]:
arr_len = arr2d.shape[1]
arr_len

10

In [24]:
for i in range(arr_len):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [27]:
arr2d[[2, 4, 6, 8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [40]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
arr_bool = arr>4
arr_bool

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [49]:
arr[arr_bool]

array([ 5,  6,  7,  8,  9, 10])

In [50]:
arr+arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [51]:
arr ** arr

array([          1,           4,          27,         256,        3125,
             46656,      823543,    16777216,   387420489, 10000000000])

In [52]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [53]:
arr*arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [54]:
arr/arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [55]:
arr%arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [58]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
arr/arr

/Users/jahanzebnaeem/opt/anaconda3/envs/NexSkill/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [60]:
1/arr

/Users/jahanzebnaeem/opt/anaconda3/envs/NexSkill/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [61]:
1+1

2

In [64]:
print(1+1)

2
